test_data = [
    {
        "event_id": "1233827",
        "event_date": "12-01-2020",
        "event_time": "15:05",
        "away_team_id": "42",
        "away_nick_name": "Texans",
        "away_city": "Houston",
        "away_rank": "21",
        "away_rank_points": "-6.00",
        "home_team_id": "63",
        "home_nick_name": "Chiefs",
        "home_city": "Kansas City",
        "home_rank": "2",
        "home_rank_points": "21.20",
    },
    {
        "event_id": "1233912",
        "event_date": "12-01-2020",
        "event_time": "18:40",
        "away_team_id": "52",
        "away_nick_name": "Seahawks",
        "away_city": "Seattle",
        "away_rank": "19",
        "away_rank_points": "-3.42",
        "home_team_id": "39",
        "home_nick_name": "Packers",
        "home_city": "Green Bay",
        "home_rank": "12",
        "home_rank_points": "5.05",
    },
    {
        "event_id": "1234560",
        "event_date": "19-01-2020",
        "event_time": "15:05",
        "away_team_id": "62",
        "away_nick_name": "Titans",
        "away_city": "Tennessee",
        "away_rank": "7",
        "away_rank_points": "10.75",
        "home_team_id": "63",
        "home_nick_name": "Chiefs",
        "home_city": "Kansas City",
        "home_rank": "2",
        "home_rank_points": "21.20",
    },
    {
        "event_id": "1234565",
        "event_date": "19-01-2020",
        "event_time": "18:40",
        "away_team_id": "39",
        "away_nick_name": "Packers",
        "away_city": "Green Bay",
        "away_rank": "12",
        "away_rank_points": "5.05",
        "home_team_id": "58",
        "home_nick_name": "49ers",
        "home_city": "San Francisco",
        "home_rank": "4",
        "home_rank_points": "15.52",
    },
]
